# Generated by Django 4.1.4 on 2023-02-02 09:11

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
