# Generated by Django 4.1.4 on 2023-02-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_authentication_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
